#!/bin/sh

replace()
{
	local file="${1:?Missing file name}"
	local match_start="${2:?Missing start pattern to match}"
	local match_end="${3:?Missing end pattern to match}"
	local old_value="${4:?Missing old value}"
	local new_value="${5:?Missing new value}"
	local flags="${6}" # Optional

	local match="\(${match_start}\)${old_value}\(${match_end}\)"
	local replace="\1${new_value}\2"

	replace_raw "$file" "$match" "$replace" "$flags" "$match_start"
}

replace "$@"
