#!/bin/sh

# Helper script to load individual scripts into current shell and make
# commands available for execution
#
# The import_config function sources the script into the current shell,
# which means that all variables and functions defined in it
# are made available.
#
# The import_commands function makes all commands in the commands/ subdir
# available for execution.
#
# Recommended usage is to source this script at the begining, call
# import_commands function to make all command available and then
# use its import_config function to source needed scripts.
#
# The base directory where the scripts to import are stored is read
# from the $LIB_DIR variable, which must be set by the caller script.
#
# EXAMPLE USAGE:
#
## BASE_DIR="$(dirname "$0")"
## LIB_DIR="$BASE_DIR/lib"
## . "$LIB_DIR/importer"
##
## import_commands
## import_config "module1"
## import_config "module2"
##
## command1
## function_from_module1

COMMANDS_DIR="$LIB_DIR/commands"
CONFIG_DIR="$LIB_DIR/config"

import_commands()
{
	# Add commands dir to $PATH, at the start to override
	# system commands if they already exists
	PATH="$COMMANDS_DIR:$PATH"
}

import_config()
{
	script_name="${1:?Missing script to import}"
	. "$CONFIG_DIR/$script_name"
}
