#!/bin/sh

BASE_DIR="$(dirname "$0")"
LIB_DIR="$BASE_DIR/lib"
. "$LIB_DIR/importer"

import_commands
import_config "dirs"

set_prop "$BUILD_APP_FILE" 'applicationId' \
		'"org.alvarogp.nettop.dev"' \
		'"org.alvarogp.nettop"'

set_string "$STRINGS_FILE" "app_name" \
		"NetTop dev" \
		"NetTop"

set_constant "$JAVA_SRC_ROOT" \
	"org.alvarogp.nettop.common.presentation.logger.AndroidLogger" \
	"private static final boolean LOG_DEBUG_MESSAGES" \
		"true" \
		"false"
